format = """
[▒](#7e602c)\
[  ](bg:#7e602c fg:#221a0f)\
[](bg:#423523 fg:#7e602c)\
$directory\
[](fg:#423523 bg:#362712)\
$git_branch\
$git_status\
[ ](fg:#362712)\
\n$character"""

[directory]
style = "fg:#d3af86 bg:#423523"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#362712"
format = '[[ $symbol $branch ](fg:#8ab1b0 bg:#362712)]($style)'

[git_status]
style = "bg:#362712"
format = '[[($all_status$ahead_behind )](fg:#8ab1b0 bg:#362712)]($style)'
ahead = '[⇡$count](fg:#221a0f bg:#889b4a)[](fg:#889b4a)'
modified = '[!$count](fg:#221a0f bg:#dc3958)[](fg:#dc3958)'
staged = '[+$count](fg:#221a0f bg:#8ab1b0)[](fg:#8ab1b0)'

[character]
success_symbol = "[❯](bold #889b4a)"
error_symbol = "[❯](bold #dc3958)"
